services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DB_CONNECTION_STRING=mongodb://mongo:27017/dailytrends
      - ENV=development
      - PORT=3000
    depends_on:
      - mongo
    command: npm run start

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
